### PR TITLE
Eyeglass and Async Tests

### PR DESCRIPTION
**Pull request by DominicBarnard**
A suggestion for a simple and flexible way to address asynchronous tests and eyeglass functionality by allowing modules to render the test sass themselves and have true parse and print the results.

### CODE REVIEW

**Comment by carljm** [comment]
This all looks good to me, except for the function name `printAssertions`. It might print some stuff as a side effect (depending entirely on what mocha reporting you configure), but what that function does is run the given CSS as test assertions using the test framework utilities you pass in; it doesn't directly print anything.

I think `makeTests` or `makeTestAssertions` or `runAssertions` or something along those lines (something that doesn't include "print" in the name) would be preferable.

**Comment by DominicBarnard** [comment]
yah I already went through a few refactors on that one, just couldn't find a good fit. runAssertions sounds great to me!

**Comment by DominicBarnard** [comment]
Actually I'm having trouble getting this to work with the example code using the before function to wait for the sass render.  It seems unless there is a describe and it function call in the same file, the before function will never be called:
```js
before(function(done){
  // this will not run unless there is a describe it block in this same file
  sass.render(eyeglass.sassOptions(), function(err, result) {
    if (err) {
      throw err;
    } else {
      sassTrue.runAssertions(result.css, describe, it);
      done();
    }
  });
});
```
My experience with node async stuff is quite limited so looking if anyone has any ideas?

**Comment by DominicBarnard** [comment]
Solved it using mocha --delay.

**Comment by DominicBarnard** [comment]
actually I think it's a [bug with node-sass](https://github.com/sass/node-sass/issues/997)

**Comment by DominicBarnard** [comment]
Yes this is working now with my fixed versions of [node-sass](https://github.com/DominicBarnard/node-sass) and [eyeglass](https://github.com/DominicBarnard/eyeglass).  If you like we can still keep the refactor to allow passing in your own rendered css if anyone thinks that might be useful?  Otherwise this can be closed.

**Comment by allejo** [comment]
@DominicBarnard do you recall how you achieved this? Were your modifications necessary to get things working with sass-true? I may be running into this same bug

**Pull request closed without merging**
