### PR TITLE
Support for nested blocks

### LINKED ISSUE #32: Feature Request: Support for nested blocks
I think tests would be clearer if there was the ability to nest blocks as in rspec where `describe` blocks can be nested to more clearly group assertions. Currently assertions can only be grouped within `test` blocks which makes it hard to group different assertions; for example testing sets of different units into the same mixin or function.

### PR DESCRIPTION
**Pull request by xi**
*Fixes #32*
*Replaces #52*

I implemented nested modules.

I had to change a lot of code, but I tried to keep the changes minimal. Most importantly, the public API is fully backwards compatible.

Note that I simplified the results module quite a bit. As far as I could see, per-test results were never used, so they just added complexity without being useful.

Due to some bigger conflicts with #51 I rewrote some of the commits in comparison to #52.

**Note**: I only tested with node-sass.

### CODE REVIEW

**Comment by xi** [comment]
Great. Already there is a conflict. Development is just too fast for me :)

**Comment by carljm** [comment]
JS here looks good to me; thanks! @mirisuzanne in your court to review Sass and merge. Maybe add a note about this in the docs?

**Comment by xi** [comment]
Thanks a lot! I didn't expect this to go through so smoothly.

**Comment by mirisuzanne** [comment]
Thank you! It's always a pleasure when someone cleans up your code and implements a new backwards-compatible feature in one clean PR. :)

**Comment by xi** [comment]
> uh oh, this change broke our reporting, and I never noticed...

I would be happy to help fixing this. But I would need more background information. How can I reproduce the issue?

**Comment by mirisuzanne** [comment]
Thanks! No worries, I fixed it in ded6b0d2c last night. We just needed to make sure assertion-results and test-results are tracked separately in order to get the proper test-count. In most cases (where each test has a single assertion) there's no difference, which is why I didn't notice it earlier. But a test with multiple assertions should still only count as a single test with a single result. Thanks again for the PR, it simplified a lot, and it's a handy feature to have!

**Pull request merged**
